[package]
name = "cursive_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
serde = "1.0.159"
something_interesting = { path = "./something_interesting/"}

